services:
  php-api:
    build:
      context: ./dc-api
      dockerfile: docker/php/Dockerfile.build # change this to Dockerfile for production build to skip tests & migrations
    volumes:
    - ./dc-api:/code
    depends_on:
      - db
    links:
      - db

  php-web:
    build:
      context: ./dc-api
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./dc-api/public:/code/public
      - ./dc-api/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./dc-api/docker/nginx/sites:/etc/nginx/sites-available
      - ./dc-api/docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    links:
      - php-api

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dc-test
      MYSQL_USER: dc
      MYSQL_PASSWORD: dc-test
      MYSQL_ROOT_PASSWORD: dc-test

  dc-frontend:
    build:
      context: ./dc-front
      dockerfile: docker/Dockerfile.build
    volumes:
      - ./dc-front:/app
    ports:
      - "80:4200"




